In [30]:
import numpy as np
print(np.__version__)

2.3.2


In [31]:
a = np.array([[1,2,3],[4,5,6]])
print(a.shape)
print(a.dtype) # datatype of the Array.


(2, 3)
int64


In [32]:
a[0]

array([1, 2, 3])

In [33]:
print(a[1,2])

6


In [34]:
a.ndim  # dimension of the Array.

print(len(a.shape) == a.ndim)

print(a.ndim)

import math 
a.size == math.prod(a.shape) #The fixed, total number of elements in array is contained in the size attribute.

True
2


True

How to create a basic Array

This section covers np.zeros(), np.ones(), np.empty(), np.arange(), np.linspace()


In [36]:
np.zeros(2)

array([0., 0.])

In [37]:
np.ones(3)

array([1., 1., 1.])

In [39]:
np.empty(2)

array([0., 0.])

In [40]:
np.arange(4)

array([0, 1, 2, 3])

In [ ]:
np.arange(2,8,2) # the first number, last number, and the step size.

array([2, 4, 6])

In [ ]:
np.linspace(0, 10, num=5) # np.linspace() to create an array with values that are spaced linearly in a specified interval:

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [45]:
# Specifying your data type

x = np.ones(2, dtype= np.int64)
print(x)

[1 1]
