In [1]:
import numpy as np
print(np.__version__)

2.3.2


## How to create a basic Array

# This section covers np.zeros(), np.ones(), np.empty(), np.arange(), np.linspace()


In [2]:
np.zeros(2)

array([0., 0.])

In [3]:
np.ones(3)

array([1., 1., 1.])

In [4]:
np.empty(2)

array([0., 0.])

In [5]:
np.arange(4)

array([0, 1, 2, 3])

In [6]:
np.arange(2,8,2) # the first number, last number, and the step size.

array([2, 4, 6])

In [7]:
np.linspace(0, 10, num=5) # np.linspace() to create an array with values that are spaced linearly in a specified interval:

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [8]:
# Specifying your data type

x = np.ones(2, dtype= np.int64)
print(x)

[1 1]


## Adding, removing, and sorting elements

# This section covers np.sort(), np.concatenate()

In [9]:
arr = np.array([2, 4, 6, 8, 9, 10,  1, 60, 89, 33, 11])
print("Sort Array By Ascending Order:",np.sort(arr))
print( "Sort Array By Descending Order:",np.sort(arr)[::-1])

Sort Array By Ascending Order: [ 1  2  4  6  8  9 10 11 33 60 89]
Sort Array By Descending Order: [89 60 33 11 10  9  8  6  4  2  1]


In [10]:
a = np.array([[1,2,3,4], [8,3,5,10]])
b = np.array([[90,45,67,33],[88,100,40,55]])
np.concatenate((a,b))

array([[  1,   2,   3,   4],
       [  8,   3,   5,  10],
       [ 90,  45,  67,  33],
       [ 88, 100,  40,  55]])

## How do you know the shape and size of an array?

# This section covers ndarray.ndim, ndarray.size, ndarray.shape

In [11]:
y = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])
print (y.ndim) # ndarray.ndim will tell you the number of axes, or dimensions, of the array.
print(y.size) # ndarray.size will tell you the total number of elements of the array. This is the product of the elements of the array’s shape
print(y.shape) # ndarray.shape will display If, for example, you have a 2-D array with 2 rows and 3 columns, the shape of your array is (2, 3).



3
24
(3, 2, 4)


## Can you reshape an array?

# This section covers arr.reshape()

In [17]:
a1 = np.arange(6)
print(a1)

[0 1 2 3 4 5]


In [19]:
b1 = a1.reshape(3,2)
print(b1)

[[0 1]
 [2 3]
 [4 5]]


In [ ]:
np.reshape(a1, shape=(1, 6), order='C')
# order: C means to read/write the elements using C-like index order

array([[0, 1, 2, 3, 4, 5]])